name: Build, Test and Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm run build
      - run: npm test
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
      - run: export ORAS_BIN_DEV=true && npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOEKEN_NO_OTP }}

  # bump-version:
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: ubuntu-latest
  #   needs: publish
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Git user
  #       run: |
  #         git config user.name "github-actions[bot]"
  #         git config user.email "github-actions[bot]@users.noreply.github.com"
  #     - name: Bump version in package.json
  #       run: |
  #         VERSION="${GITHUB_REF#refs/tags/v}"
  #         jq ".version = \"$VERSION\"" package.json > package.tmp.json
  #         mv package.tmp.json package.json
  #         git add package.json
  #         git commit -m "chore: bump version to $VERSION [skip ci]"
  #         git push
